FROM node:18-alpine AS builder

WORKDIR /app
COPY frontend/package*.json ./
RUN npm install --omit=dev

COPY frontend/ ./
RUN npm run build

# Use nginx for serving
FROM nginx:alpine
COPY --from=builder /app/build /usr/share/nginx/html
COPY nginx/nginx.conf /etc/nginx/nginx.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
